// halo judith

const c0smicbliss = [
	`https://soundcloud.com/dimasramdhans/japanese-denim`,
	`https://soundcloud.com/dimasramdhans/romance-de-amour-and-a-classic-i-forgot`,
	`https://soundcloud.com/dimasramdhans/cayman-islands`,
	`https://soundcloud.com/dimasramdhans/bring-me-the-horizon-shadow-moses-instrumental-cover`,
	`https://soundcloud.com/dimasramdhans/meet-me-in-amsterdam-rini-cover`,
	`https://soundcloud.com/dimasramdhans/loves-run-out-circa-waves-cover`,
	`https://soundcloud.com/dimasramdhans/you-might-be-sleeping`,
	`https://soundcloud.com/dimasramdhans/pilu-membiru`,
	`https://soundcloud.com/dimasramdhans/reality-club-alexandra-cover`,
	`https://soundcloud.com/dimasramdhans/rex-orange-county-pluto-projector-cover`,
	`https://soundcloud.com/dimasramdhans/rex-orange-county-happiness-cover`,
	`https://soundcloud.com/dimasramdhans/tamino-habibi-voice-cover`,
	`https://soundcloud.com/dimasramdhans/i-love-you`,
	`https://soundcloud.com/dimasramdhans/cry`,
	`https://soundcloud.com/dimasramdhans/song-for-you`,
	`https://soundcloud.com/dimasramdhans/chelsea-smile`,
	`https://soundcloud.com/dimasramdhans/hozier-talk-voice-cover`,
	`https://soundcloud.com/dimasramdhans/one-more-love-song`,
	`https://soundcloud.com/dimasramdhans/rex-orange-country-sunflower-cover`,
	`https://soundcloud.com/dimasramdhans/someone-like-you`,
	`https://soundcloud.com/dimasramdhans/architects-animals-instrumental-cover`,
	`https://soundcloud.com/dimasramdhans/local-natives-mt-washington`,
	`https://soundcloud.com/dimasramdhans/joji-worldstar-money-interlude-cover`,
	`https://soundcloud.com/dimasramdhans/bring-me-the-horizon-drown-cover`,
	`https://soundcloud.com/dimasramdhans/tamino-indigo-night-cover`,
	`https://soundcloud.com/dimasramdhans/joji-i-dont-wanna-waste-my-time-cover`,
	`https://soundcloud.com/dimasramdhans/brockhampton-waste-cover`,
	`https://soundcloud.com/dimasramdhans/why-why-why-yonlapa-cover`,
	`https://soundcloud.com/dimasramdhans/too-deep-to-turn-back-daniel-caesar-cover`,
	`https://soundcloud.com/dimasramdhans/idontwannabeyouanymore-billie-eilish-acoustic-cover`,
	`https://soundcloud.com/dimasramdhans/speaking-terms-snail-mail-cover`,
	`https://soundcloud.com/dimasramdhans/another-one-mac-demarco-cover`,
	`https://soundcloud.com/dimasramdhans/entah-ingin-ke-mana-danilla-cover`,
	`https://soundcloud.com/dimasramdhans/song-for-you-rhye-cover`,
	`https://soundcloud.com/dimasramdhans/my-mistakes-were-made-for-you-the-last-shadow-puppets-cover`,
	`https://soundcloud.com/dimasramdhans/this-old-dog-mac-demarco-cover-1`,
	`https://soundcloud.com/dimasramdhans/ikat-aku-di-tulang-belikatmu`,
	`https://soundcloud.com/dimasramdhans/onemorelovesong-mixdown`,
	`https://soundcloud.com/dimasramdhans/let-my-baby-stay-mac-demarco-cover`,
	`https://soundcloud.com/dimasramdhans/the-less-i-know-the-better-tame-impala-final-cover`,
	`https://soundcloud.com/dimasramdhans/affection-cigarettes-after-sex-cover`,
	`https://soundcloud.com/dimasramdhans/k-cigarettes-after-sex-cover`,
	`https://soundcloud.com/dimasramdhans/melebur-semesta-sal-priadi-guitarlele-cover`,
	`https://soundcloud.com/dimasramdhans/december-efek-rumah-kaca-cover`,
	`https://soundcloud.com/dimasramdhans/lagu-kesepian-efek-rumah-kaca-cover`,
	`https://soundcloud.com/dimasramdhans/dreamin-again-khdn-dimas-ramdhan`,
	`https://soundcloud.com/dimasramdhans/pasar-bisa-diciptakan-efek-rumah-kaca-cover-1`,
	`https://soundcloud.com/dimasramdhans/the-only-one-who-knows-arctic-monkeys-cover`,
	`https://soundcloud.com/dimasramdhans/you-might-be-sleeping-jakob-ogawa-clairo-cover`,
	`https://soundcloud.com/dimasramdhans/everytime-boy-pablo-cover`,
	`https://soundcloud.com/dimasramdhans/the-less-i-know-the-better-tame-impala-cover-i`,
	`https://soundcloud.com/dimasramdhans/heart-shaped-box-cover-dikit`,
	`https://soundcloud.com/dimasramdhans/love-song-tesla-cover`,
	`https://soundcloud.com/dimasramdhans/intro-nothing-else-matter`

]

module.exports = c0smicbliss;